build/linux: Do not allow creating gimp snap with master gimp
Also, do some improvements on babl/gegl check.

(cherry picked from commit 67040c7f99b4fffb8fa11c24a378788746b377fc)

diff --git a/build/linux/snap/snapcraft.yaml b/build/linux/snap/snapcraft.yaml
--- a/build/linux/snap/snapcraft.yaml
+++ b/build/linux/snap/snapcraft.yaml
@@ -92,7 +92,7 @@ parts:
     source-depth: 1
     override-pull: |
       if [ "$SNAPCRAFT_PROJECT_GRADE" != 'stable' ] && [ "$SNAPCRAFT_PROJECT_NAME" = 'gimp' ]; then
-        printf '\033[31m(ERROR)\033[0m non-tagged source can not be deployed to gimp snap. Please, change grade to stable\n' 
+        printf '\033[31m(ERROR)\033[0m non-tagged source can not be deployed to gimp snap. Please, change grade value to stable\n' 
         exit 1
       fi
       if [ "$SNAPCRAFT_PROJECT_GRADE" != 'stable' ] && [ "$SNAPCRAFT_PROJECT_NAME" != 'gimp' ]; then
@@ -116,6 +116,10 @@ parts:
     source: https://gitlab.gnome.org/GNOME/gegl.git
     source-depth: 1
     override-pull: |
+      if [ "$SNAPCRAFT_PROJECT_GRADE" != 'stable' ] && [ "$SNAPCRAFT_PROJECT_NAME" = 'gimp' ]; then
+        printf '\033[31m(ERROR)\033[0m non-tagged source can not be deployed to gimp snap. Please, change grade value to stable\n' 
+        exit 1
+      fi
       if [ "$SNAPCRAFT_PROJECT_GRADE" != 'stable' ] && [ "$SNAPCRAFT_PROJECT_NAME" != 'gimp' ]; then
         craftctl default
       else
@@ -147,6 +151,10 @@ parts:
     source-type: local
     override-pull: |
       craftctl default
+      if ! git describe --tags --exact-match >/dev/null 2>&1 && [ "$SNAPCRAFT_PROJECT_NAME" = 'gimp' ]; then
+        printf '\033[31m(ERROR)\033[0m non-tagged source can not be deployed to gimp snap. Please, checkout gimp repo to a tagged commit\n' 
+        exit 1
+      fi
       craftctl set version="$(awk -F"'" '/version:/ {print $2; exit}' $CRAFT_PART_SRC/meson.build)"
     build-environment: *SNAP_ENVIRON
     plugin: meson
