check for xmllint and xsltproc but don't require these tools.
2004-05-01  Sven Neumann  <sven@gimp.org>

	* configure.in: check for xmllint and xsltproc but don't require
	these tools.

	* menus/Makefile.am
	* tips/Makefile.am: simplified "validate" targets.

diff --git a/menus/Makefile.am b/menus/Makefile.am
--- a/menus/Makefile.am
+++ b/menus/Makefile.am
@@ -33,14 +33,11 @@ EXTRA_DIST = \
 
 
 validate: $(menudata_DATA)
-	@( xmllint=`which xmllint`; \
-	  if test x$$xmllint != x && test -x $$xmllint; then \
-	    for menu in $(menudata_DATA); do \
-	      $$xmllint --noout --valid $$menu || \
-	      ( echo "* $$menu INVALID *"; exit 1; ) ; \
-	    done; \
-	  else \
-	    echo "Can't find xmllint to validate the menu files; proceed with fingers crossed..."; \
-	  fi )
+if HAVE_XMLLINT
+	@for menu in $(menudata_DATA); do \
+	   $(XMLLINT) --noout --valid $$menu || \
+	   ( echo "* $$menu INVALID *"; exit 1; ) ; \
+	done
+endif
 
 dist-hook: validate
diff --git a/tips/Makefile.am b/tips/Makefile.am
--- a/tips/Makefile.am
+++ b/tips/Makefile.am
@@ -77,12 +77,9 @@ update-po: $(srcdir)/$(GETTEXT_PACKAGE)-tips.pot
 	done
 
 validate: update-po gimp-tips.xml
-	( xmllint=`which xmllint`; \
-	  if test x$$xmllint != x && test -x $$xmllint; then \
-	    $$xmllint --noout --valid gimp-tips.xml || \
-	      ( echo "* gimp-tips.xml INVALID *"; exit 1; ) \
-	  else \
-	    echo "Can't find xmllint to validate gimp-tips.xml; proceed with fingers crossed..."; \
-	  fi )
+if HAVE_XMLLINT
+	@$(XMLLINT) --noout --valid gimp-tips.xml || \
+	  ( echo "* gimp-tips.xml INVALID *"; exit 1; )
+endif
 
 dist-hook: validate
